### ISSUE TITLE
Unsupported certificate purpose when creating bundle

### ISSUE THREAD

**Issue by incaseoftrouble** [rauc/rauc#729]
EDIT: Problem solved, two subsequent issues 1) `rauc bundle` should complain if config file given via `-c <file>` does not exist 2) it should be possible to specify `check-purpose=codesign` on the CLI (e.g. `--check-purpose=<purpose>`)

I'm creating a bundle using `rauc bundle --key=<key> --cert=<cert> --keyring=<ca> --intermediate=<intermediate> dir`. This fails with `Failed to create bundle: failed to sign manifest: signature verification failed: Verify error:unsupported certificate purpose`. 
Without `--keyring`, i.e. without verification on the host, bundle creation works. I suspect that an error occurs when parsing the keyring file.

The certificate chain is valid:
```
$ openssl verify -CAfile <ca> -untrusted <intermediate> <cert>
<cert>: OK
$  openssl verify -CAfile <(cat <intermediate> <ca>) <cert>
<cert>: OK
```
I also verified the  X509v3 Subject/Authority Key Identifier fields.

I have a "normal" root -> intermediate -> signing setup, where
```
[ v3_root ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true
keyUsage = critical, digitalSignature, cRLSign, keyCertSign

[ v3_intermediate ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints = critical, CA:true, pathlen:0
keyUsage = critical, digitalSignature, cRLSign, keyCertSign

[ v3_codesign ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
basicConstraints = CA:FALSE
extendedKeyUsage = critical, codeSigning
```
with the last according to the [docs](https://rauc.readthedocs.io/en/latest/advanced.html#certificate-key-usage-attributes)

This might be related to #713 . The problem also occurs when I run `rauc` with `-c system.conf` with a `[keyring] check-purpose=codesign`

My version:
```
$ rauc --version
rauc 1.5.1
```

**Comment by incaseoftrouble** [comment]
Addition: Reading throught the docs again:

> Also, you can optionally use extendedKeyUsage attributes on intermediate CA certificates to limit which ones are allowed to issue code signing certificates.

So it might be the case that the root / intermediate certs also need the codeSigning usage?

**Comment by jluebbe** [comment]
The keyUsage/extendedKeyUsage looks fine (the check is implemented in https://github.com/rauc/rauc/blob/master/src/signature.c#L21). I would have hoped that `-c system.conf` with the purpose should be enough for `rauc bundle`. You could make `setup_x509_store()` more verbose to verify that the correct purpose is configured.

**Comment by incaseoftrouble** [comment]
More info: With `system.conf` having `check-purpose=any`, it works.

Running with `G_MESSAGES_DEBUG="all"` reveals the following:

intermediate:
```
                object: X509v3 Key Usage (2.5.29.15)
                critical: TRUE
                value:
                  0000 - 03 02 01 86                              ....

                object: X509v3 Extended Key Usage (2.5.29.37)
                critical: TRUE
                value:
                  0000 - 30 0a 06 08 2b 06 01 05-05 07 03 03      0...+.......
```
and sigining:
```
                object: X509v3 Basic Constraints (2.5.29.19)
                critical: BOOL ABSENT
                value:
                  0000 - 30 00                                    0.

                object: X509v3 Extended Key Usage (2.5.29.37)
                critical: TRUE
                value:
                  0000 - 30 0a 06 08 2b 06 01 05-05 07 03 03      0...+.......
```
